/* This file is designed to allow local variations between the Solaris, Linux,
   and Linux Local versions of the code so we can have a single source tree
   and just modify this file and the Makefile for the variations.
*/

#define MeSH_Version 2021
#define DisclaimerStr "Disclaimer: The MeSH on Demand MeSH Terms are machine generated by MTI and DO NOT reflect any human review. MTI may recommend MeSH Terms not explicitly found in the text and may not recommend MeSH Terms that are in the text. This is a result of machine logic that attempts to emulate human indexer behavior in characterizing biomedically relevant parts of the text. These results will undoubtedly differ from any human-generated indexing."

#define MAXHOSTNAMELEN 1024  /* Needed on Linux side */

/* For btree_query.c */

#define database_home "/nfsvol/nls/II_Group_WorkArea/MTI/Data_Tables/2021"
/*****************************************************************************/

/* For MTI.c */

#define default_TexToolHost "skr4"
#define MAXPTS 500
#define MAXMHSHS 5000
#define CATPTS "/nfsvol/nls/II_Group_WorkArea/MTI/Resources/PTs_2021.txt"
#define LEAFNODEMHS "/nfsvol/nls/MEDLINE_Baseline_Repository/MeSH/2021/leaf_dashes/finalOrderedCleanMHETLeafNodes_SCRs_A2B_bucket.txt"
#define ISOTOPE_ABBREVS "/nfsvol/nls/II_Group_WorkArea/MTI/Resources/Data_2021/check_Isotopes.txt"
#define LEAD_JOURNAL_CHECKS "/nfsvol/nls/II_Group_WorkArea/MTI/Validation/identify_Lead_Journals/lead_lookforCategory_by_Journal.txt"
#define JAVA_VERSION "/nfsvol/nls/II_Group_WorkArea/MTI/Resources/Linux/java/bin/java"
#define ANTONIOCMD "/nfsvol/nls/II_Group_WorkArea/MTI/Resources/Antonio/Server/runASCII_1.sh"
#define COMMANDSTR "/nfsvol/nls/bin/metamap18 -Z 2020AB -iDN --lexicon db -Q 0 --no_nums ALL --prune 50"
#define COMMANDSTR_AUTO "/nfsvol/nls/bin/metamap18 -Z 2020AB -N --lexicon db -Q 0 --no_nums ALL --prune 50"
#define COMMANDSTR_MoD "/nfsvol/nls/bin/metamap18 -Z 2020AB -iDN --lexicon db -Q 0 --blanklines 0 --no_nums ALL --prune 50"
#define COMMANDSTR_WSD "/nfsvol/nls/bin/metamap18 -Z 2020AB -iDNy --lexicon db -Q 0"
#define COMMANDIISTR "/nfsvol/nls/bin/metamap18 -Z 2020AB -dN -R 'MSH' --lexicon db -Q 0"
#define COMMANDIISTR_WSD "/nfsvol/nls/bin/metamap18 -dNy -R 'MSH' --lexicon db -Q 0"
#define ENV_JAVA_LIB "CLASSPATH=/nfsvol/nls/II_Group_WorkArea/MTI/Resources/lib"
#define ENV_JAVA_HOME "JAVA_HOME=/nfsvol/nls/II_Group_WorkArea/MTI/Resources/Linux/java"
#define ENV_LD_LIB "LD_LIBRARY_PATH=/usr/lib:/usr/local/lib"
#define FIRSTLINE_FILE "/nfsvol/nls/II_Group_WorkArea/MTI/Resources/FirstLineJournals.txt"
#define MTI_REVIEW_JOURNALS_FILE "/nfsvol/nls/II_Group_WorkArea/MTI/Resources/MTI_Review_Journals.txt"
#define MTI_AUTO_JOURNALS_FILE "/nfsvol/nls/II_Group_WorkArea/MTI/Resources/MTI_AUTO_Journals.txt"
#define PTs_to_INDEX_FILE "/nfsvol/nls/II_Group_WorkArea/MTI/Validation/PTs/final_Index_PT_list.txt"
#define ACTIVEJOURNALS "/nfsvol/nls/II_Group_WorkArea/MTI/Resources/activeJournals.txt"
#define USA_CaseSenTrigFile "/nfsvol/nls/II_Group_WorkArea/MTI/Validation/USATriggers_CaseSen.txt"
#define OLDMEDLINE_MAPPINGS "/nfsvol/nls/II_Group_WorkArea/MTI/Resources/OLDMEDLINE_MappingsList.txt"
#define OLDMEDLINE_COMBINED_MAPPINGS "/nfsvol/nls/II_Group_WorkArea/MTI/Resources/OLDMEDLINE_MHSH_Mappings.txt"
#define ANIMAL_TRIGGERS_FILE "/nfsvol/nls/II_Group_WorkArea/MTI/Resources/Data_2021/AnimalTriggers.txt"
#define RNDTTH_FILE "/nfsvol/nls/II_Group_WorkArea/MTI/Resources/TexTool.txt"

/*****************************************************************************/

/* For parseMARC.c */

#define REPL_FILE "/nfsvol/nls/MEDLINE_Baseline_Repository/tools/reference/replacements_XML_MEDLINE"
#define QUALIFIERS "/nfsvol/nls/MEDLINE_Baseline_Repository/MeSH/2021/qlist"
#define QUALSII "/nfsvol/nls/II_Group_WorkArea/MTI/Resources/MTI_QualifiersFiltered"
#define LCSH2MSH_FILE "/nfsvol/nls/II_Group_WorkArea/MTI/Resources/newLCH2MSH_2021"
/*****************************************************************************/
